#!/usr/bin/env python3
"""
Extracts quest names and reward data from FFXIV 1.0 client DAT files.
Generates SQL UPDATE statements for the gamedata_quests table.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dat_reader import load_schema, load_sheet_info, read_sheet_data

EXP_BASE_PER_UNIT = {
    5: 40, 10: 80, 15: 100, 17: 120, 18: 130,
    20: 170, 21: 200, 24: 250, 25: 270,
    30: 380, 31: 450, 35: 560,
    40: 710, 45: 890, 50: 1100
}


def interpolate_exp_base(level):
    if level in EXP_BASE_PER_UNIT:
        return EXP_BASE_PER_UNIT[level]
    keys = sorted(EXP_BASE_PER_UNIT.keys())
    if level <= keys[0]:
        return EXP_BASE_PER_UNIT[keys[0]]
    if level >= keys[-1]:
        return EXP_BASE_PER_UNIT[keys[-1]]
    lo = keys[0]
    hi = keys[-1]
    for k in keys:
        if k <= level:
            lo = k
        if k >= level:
            hi = k
            break
    lo_val = EXP_BASE_PER_UNIT[lo]
    hi_val = EXP_BASE_PER_UNIT[hi]
    if hi == lo:
        return lo_val
    frac = (level - lo) / (hi - lo)
    return int(lo_val + frac * (hi_val - lo_val))


def extract_rewards(reward_row, quest_level):
    exp_reward = 0
    gil_reward = 0
    items = []
    for slot in range(16):
        base = slot * 13
        status = reward_row[base]
        rtype = reward_row[base + 1]
        c3 = reward_row[base + 3]
        vals = reward_row[base + 5:base + 9]
        if status not in (100, 302):
            continue
        if rtype == -12:
            if vals[0] > 0:
                exp_reward = max(exp_reward, vals[0])
        elif rtype == -13:
            if vals[0] > 0 and quest_level > 0:
                base_exp = interpolate_exp_base(quest_level)
                computed = base_exp * vals[0]
                exp_reward = max(exp_reward, computed)
        elif rtype == -2:
            if vals[0] > 0:
                gil_reward = max(gil_reward, vals[0])
        elif rtype in (-4, -8, -10):
            if c3 > 0 and status == 100:
                qty = max(1, vals[0]) if vals[0] > 0 else 1
                if len(items) < 4:
                    items.append((c3, qty))
    return exp_reward, gil_reward, items


def main():
    output_file = sys.argv[1] if len(sys.argv) > 1 else None
    out = open(output_file, 'w', encoding='utf-8') if output_file else sys.stdout

    print("Loading game data...", file=sys.stderr)
    sheets = load_schema()

    quest_sub = load_sheet_info(sheets['quest'])
    quest_rows = read_sheet_data(quest_sub[0])

    reward_sub = load_sheet_info(sheets['quest_new_reward'])
    reward_rows = read_sheet_data(reward_sub[0])

    text_sub = load_sheet_info(sheets['xtx/quest'])
    text_rows = read_sheet_data(text_sub[1])

    out.write("-- ============================================================\n")
    out.write("-- FFXIV 1.0 Quest Data (auto-extracted from client DAT files)\n")
    out.write("-- Generated by extract_quest_data.py\n")
    out.write("-- ============================================================\n\n")

    out.write("-- SECTION 1: Quest Names\n")
    out.write("-- Updates quest names from [en] placeholders to actual English names\n\n")

    name_count = 0
    for qid in sorted(text_rows.keys()):
        if qid < 110000:
            continue
        name = text_rows[qid][0]
        if not name or name == "[en]":
            continue
        escaped = name.replace("'", "\\'")
        out.write(f"UPDATE `gamedata_quests` SET `name` = '{escaped}' WHERE `id` = {qid} AND `name` = '[en]';\n")
        name_count += 1

    out.write(f"\n-- {name_count} quest names extracted\n\n")

    out.write("-- ============================================================\n")
    out.write("-- SECTION 2: Quest Rewards\n")
    out.write("-- exp, gil, and item rewards extracted from quest_new_reward sheet\n\n")

    reward_count = 0
    for qid in sorted(quest_rows.keys()):
        if qid < 110000:
            continue
        if qid not in reward_rows:
            continue

        quest_level = quest_rows[qid][2]
        exp, gil, items = extract_rewards(reward_rows[qid], quest_level)

        if exp == 0 and gil == 0 and len(items) == 0:
            continue

        quest_name = ""
        if qid in text_rows:
            quest_name = text_rows[qid][0]

        parts = []
        if exp > 0:
            parts.append(f"`expReward` = {exp}")
        if gil > 0:
            parts.append(f"`gilReward` = {gil}")
        for i, (item_id, qty) in enumerate(items):
            parts.append(f"`itemReward{i+1}` = {item_id}")
            parts.append(f"`itemReward{i+1}Qty` = {qty}")

        if parts:
            set_clause = ", ".join(parts)
            comment = f" -- {quest_name} (Lv{quest_level})" if quest_name else ""
            out.write(f"UPDATE `gamedata_quests` SET {set_clause} WHERE `id` = {qid};{comment}\n")
            reward_count += 1

    out.write(f"\n-- {reward_count} quests with rewards extracted\n")

    if output_file:
        out.close()
    print(f"Done: {name_count} names, {reward_count} rewards", file=sys.stderr)


if __name__ == '__main__':
    main()
